In [1]:
import pandas as pd

pd.set_option('display.min_rows', 30)# 显示行数
# 1.读取数据
df = pd.read_csv('data/sales.csv')

# 2. 数据清洗
# 2.1 缺失值处理
df.isnull()# 查看缺失值

# 2.1.1 删除缺失值
# df.dropna()# 删除缺失值所在行axis=0
# df = df.dropna(axis=1) # 删除缺失值所在列axis=1
# df
# 2.1.2 填充缺失值
df.fillna('--')# 填充缺失值
df.ffill()# 填充缺失值,用前一个值填充
df.bfill()# 填充缺失值,用后一个值填充

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    2782973956  家居用品    枕头     3  118     广州   银行卡  2025-06-14
1    3862337541    图书    漫画     2  290     福州  微信支付  2025-06-02
2    9826076680    食品    牛奶     5  -78     福州  微信支付  2025-06-28
3    5949577226  电子产品  蓝牙耳机     9  297     杭州   银行卡  2025-06-07
4    9708761103    图书    小说     9  153     合肥   支付宝  2025-06-14
5    3577253908    服装    T恤     8  289     合肥   银行卡  2025-06-26
6    9826076680  电子产品  蓝牙耳机     1   82     成都   支付宝  2025-06-07
7    3971653655  家居用品    枕头    10  319     成都  微信支付  2025-06-27
8    2331463704    食品    牛奶     1  376     北京   支付宝  2025-06-06
9    5027895059  电子产品  蓝牙耳机     5  151     福州   支付宝  2025-06-18
10   1113729050  家居用品    台灯     1  243     武汉    现金  2025-06-27
11   8252921620    食品    牛奶     3  131     合肥  微信支付  2025-06-25
12   1658050590    食品   巧克力     3  345     郑州   支付宝  2025-06-05
13   6993352739    食品    牛奶     6  171     天津    现金  2025-06-16
14   1232889892    食品    海苔     6  278     北京    现金  2025-06-01
..          ...   ...   ...   ...  ...    ...   ...         ...
985  3897026524  家居用品   保温杯     4  310     武汉  微信支付  2025-06-13
986  5672595423    食品   巧克力     2  271     天津  微信支付  2025-06-16
987  1136355295  家居用品    毯子     2  130     重庆   支付宝  2025-06-07
988  8775649251    服装    T恤     3   61     合肥   银行卡  2025-06-17
989  8151637988  家居用品    台灯     4  152     武汉   支付宝  2025-06-01
990  2654400483  家居用品    台灯     8  310     深圳   银行卡  2025-06-28
991  7561426920    图书    杂志     7  201     广州   银行卡  2025-06-09
992  2000381929    服装    帽子     6  186     天津    现金  2025-06-15
993  5400756202    图书    绘本     6  333     郑州   银行卡  2025-06-04
994  4421685228  电子产品  智能音箱     7  395     杭州   支付宝  2025-06-26
995  5112770542  电子产品   充电宝    10  110     昆明    现金  2025-06-04
996  9807677424    服装    T恤     2  357     天津  微信支付  2025-06-18
997  1383827443  家居用品   收纳盒     3  264     重庆    现金  2025-06-15
998  1475477497    食品    牛奶     3  390     南京   银行卡  2025-06-23
999  3479681020    图书    小说     1  385     南京  微信支付  2025-06-01

[1000 rows x 8 columns]

In [7]:
#2.2重复值处理
#2.2.1 查看重复值
df.duplicated()# 查看重复值
df.duplicated(subset=['订单号'])# 查看重复值(根据订单号)

# 2.2.2 删除重复值
df.drop_duplicates(subset=['订单号'], keep=False)# keep = 'first'保留第一个, keep = 'last'保留最后一个, keep = False不保留(所有)

            订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0    2782973956  家居用品    枕头     3  118     广州   银行卡  2025-06-14
1    3862337541    图书    漫画     2  290     福州  微信支付  2025-06-02
3    5949577226  电子产品  蓝牙耳机     9  297     杭州   银行卡  2025-06-07
4    9708761103    图书    小说     9  153     合肥   支付宝  2025-06-14
5    3577253908    服装    T恤     8  289     合肥   银行卡  2025-06-26
7    3971653655  家居用品    枕头    10  319     成都  微信支付  2025-06-27
8    2331463704    食品    牛奶     1  376     北京   支付宝  2025-06-06
9    5027895059  电子产品  蓝牙耳机     5  151     福州   支付宝  2025-06-18
10   1113729050  家居用品    台灯     1  243     武汉    现金  2025-06-27
11   8252921620    食品    牛奶     3  131     合肥  微信支付  2025-06-25
12   1658050590    食品   巧克力     3  345     郑州   支付宝  2025-06-05
13   6993352739    食品    牛奶     6  171     天津    现金  2025-06-16
14   1232889892    食品    海苔     6  278     北京    现金  2025-06-01
15   5158180901  家居用品    枕头    10  221     北京    现金  2025-06-29
16   9594499109    图书    绘本     4   70     北京   支付宝  2025-06-25
..          ...   ...   ...   ...  ...    ...   ...         ...
985  3897026524  家居用品   保温杯     4  310     武汉  微信支付  2025-06-13
986  5672595423    食品   巧克力     2  271     天津  微信支付  2025-06-16
987  1136355295  家居用品    毯子     2  130     重庆   支付宝  2025-06-07
988  8775649251    服装    T恤     3   61     合肥   银行卡  2025-06-17
989  8151637988  家居用品    台灯     4  152     武汉   支付宝  2025-06-01
990  2654400483  家居用品    台灯     8  310     深圳   银行卡  2025-06-28
991  7561426920    图书    杂志     7  201     广州   银行卡  2025-06-09
992  2000381929    服装    帽子     6  186     天津    现金  2025-06-15
993  5400756202    图书    绘本     6  333     郑州   银行卡  2025-06-04
994  4421685228  电子产品  智能音箱     7  395     杭州   支付宝  2025-06-26
995  5112770542  电子产品   充电宝    10  110     昆明    现金  2025-06-04
996  9807677424    服装    T恤     2  357     天津  微信支付  2025-06-18
997  1383827443  家居用品   收纳盒     3  264     重庆    现金  2025-06-15
998  1475477497    食品    牛奶     3  390     南京   银行卡  2025-06-23
999  3479681020    图书    小说     1  385     南京  微信支付  2025-06-01

[998 rows x 8 columns]

In [ ]:
# 2.3异常值处理
#2.3.1 查看异常值
df[df['单价'] < 0]

# 2.3.2 删除异常值
df.drop(df[df['单价']<0].index)

# 2.3.3 修复异常值
df['单价'] = df['单价'].abs()# 绝对值
df

# 2.4 数据格式处理
df["订单日期"] = df["订单日期"].str.replace("/", "-")
df